services:
  AuthDataSourceProvider:
    class: //@inviqa/viper-gateway-service-auth[DrupalAuthDataSourceProvider]
    arguments:
      - '@DrupalRestClientProvider'
      - '%env(AUTH_TOKEN_SECRET)%'
