parameters:
  drupal:
    graphql:
      client: ~
      http:
        uri: https://drupal-int.viper.webpipeline.net/graphql
    rest:
      client:
        baseURL: https://drupal-int.viper.webpipeline.net
    defaultLocales:
      EN: en_GB
      DE: de_DE
    logger:
      prefix: drupal
      level: info
      timestamp: true

services:
  # REST
  DrupalRestClientProvider:
    class: //@inviqa/viper-backend-drupal[DrupalRestClientProvider]
    arguments: ['@DrupalAxiosClientBuilder']

  DrupalAxiosClientBuilder:
    class: //@inviqa/viper-axios[AxiosClientBuilder]
    factory: ['@AxiosClientBuilderFactory', 'create']
    arguments:
      - '%drupal.rest.client%'
      - '@DrupalAxiosClientBuilderPluginList'

  DrupalAxiosClientBuilderPluginList:
    class: //@inviqa/viper-axios[AxiosClientBuilderPluginList]
    factory: ['@AxiosClientBuilderPluginListFactory', 'create']
    arguments: ['@DrupalAxiosClientLoggerPlugin']

  DrupalAxiosClientLoggerPlugin:
    class: //@inviqa/viper-axios[AxiosClientLoggerPlugin]
    factory: ['@AxiosClientLoggerPluginFactory', 'create']
    arguments: ['@DrupalLogger']

  # GraphQL
  DrupalGraphqlClientProvider:
    class: //@inviqa/viper-backend-drupal[DrupalGraphqlClientProvider]
    arguments:
      - '@DrupalApolloClientBuilder'
      - '@DrupalDocumentOverrides'

  DrupalDocumentOverrides:
    class: //@inviqa/viper-backend-graphql[DocumentOverrides]

  DrupalApolloClientBuilder:
    class: //@inviqa/viper-apollo[ApolloClientBuilder]
    factory: ['@ApolloClientBuilderFactory', 'create']
    arguments:
      - '%drupal.graphql.client%'
      - '@DrupalApolloLinkProviders'

  DrupalApolloLinkProviders:
    class: //@inviqa/viper-apollo[ApolloLinkProviderList]
    factory: ['@ApolloLinkProviderListFactory', 'create']
    arguments:
      - '@DrupalLoggerLinkProvider'
      - '@DrupalHttpLinkProvider'

  DrupalHttpLinkProvider:
    class: //@inviqa/viper-apollo[HttpLinkProvider]
    factory: ['@HttpLinkProviderFactory', 'create']
    arguments: ['%drupal.graphql.http%']

  DrupalLoggerLinkProvider:
    class: //@inviqa/viper-apollo[LoggerLinkProvider]
    factory: ['@LoggerLinkProviderFactory', 'create']
    arguments: ['@DrupalLogger']

  DrupalLogger:
    class: //@inviqa/viper-logger[LogLevelNextLogger]
    arguments:
      - '%drupal.logger.prefix%'
      - '%drupal.logger.level%'
      - '%drupal.logger.timestamp%'
