services:
  ContentRoutingDataSourceProvider:
    class: //@inviqa/viper-gateway-service-routing[DrupalRoutingDataSourceProvider]
    arguments:
      - '@DrupalGraphqlClientProvider'
      - '@ContentRoutingDataTransformer'

  ContentRoutingDataTransformer:
    class: //@inviqa/viper-gateway-service-routing[DrupalRoutingDataTransformer]
    arguments: ['%drupal.defaultLocales%']
