parameters:
  auth:
    path: /_internal/auth

services:
  AuthService:
    class: //@inviqa/viper-gateway-service-auth[AuthService]
    arguments:
      - '%auth.path%'
      - './node_modules/@inviqa/viper-gateway-service-auth/src/typedef/schema.graphql'
      - '@AuthResolverProvider'
      - '@AuthDataSource'
      - '@GatewayServiceRunner'
      - '@AuthApolloServerBuilder'

  AuthResolverProvider:
    class: //@inviqa/viper-gateway-service-auth[AuthResolverProvider]

  AuthDataSource:
    class: //@inviqa/viper-gateway-service-auth[DrupalAuthDataSource]
    arguments:
      - '%env(AUTH_TOKEN_SECRET)%'
      - '%drupal.rest.baseUrl%'

  AuthApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
