services:
  AuthService:
    class: //@inviqa/viper-gateway-service-auth[AuthService]
    arguments:
      - '%services.auth.path%'
      - '%services.auth.schema%'
      - '@AuthResolverProvider'
      - '@AuthDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@AuthApolloServerBuilder'

  AuthResolverProvider:
    class: //@inviqa/viper-gateway-service-auth[AuthResolverProvider]

  AuthApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
