services:
  CatalogService:
    class: //@inviqa/viper-gateway-service-catalog[CatalogService]
    arguments:
      - '%services.catalog.path%'
      - '%services.catalog.schema%'
      - '@CatalogResolverProvider'
      - '@CatalogDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@CatalogApolloServerBuilder'

  CatalogResolverProvider:
    class: //@inviqa/viper-gateway-service-catalog[CatalogResolverProvider]

  CatalogApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
