parameters:
  catalog:
    path: /_internal/catalog

services:
  CatalogService:
    class: //@inviqa/viper-gateway-service-catalog[CatalogService]
    arguments:
      - '%catalog.path%'
      - './node_modules/@inviqa/viper-gateway-service-catalog/src/typedef/*.graphql'
      - '@CatalogResolverProvider'
      - '@CatalogDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@CatalogApolloServerBuilder'

  CatalogResolverProvider:
    class: //@inviqa/viper-gateway-service-catalog[CatalogResolverProvider]

  CatalogApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
