services:
  ConfigService:
    class: //@inviqa/viper-gateway-service-config[ConfigService]
    arguments:
      - '%services.config.path%'
      - '%services.config.schema%'
      - '@ConfigResolverProvider'
      - '@ConfigDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@ConfigApolloServerBuilder'

  ConfigResolverProvider:
    class: //@inviqa/viper-gateway-service-config[ConfigResolverProvider]

  ConfigApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
