services:
  ContentService:
    class: //@inviqa/viper-gateway-service-content[ContentService]
    arguments:
      - '%services.content.path%'
      - '%services.content.schema%'
      - '@ContentResolverProvider'
      - '@ContentDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@ContentApolloServerBuilder'

  ContentResolverProvider:
    class: //@inviqa/viper-gateway-service-content[ContentResolverProvider]

  ContentApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
