parameters:
  content:
    path: /_internal/content

services:
  ContentService:
    class: //@inviqa/viper-gateway-service-content[ContentService]
    arguments:
      - '%content.path%'
      - './node_modules/@inviqa/viper-gateway-service-content/src/typedef/schema.graphql'
      - '@ContentResolverProvider'
      - '@ContentDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@ContentApolloServerBuilder'

  ContentResolverProvider:
    class: //@inviqa/viper-gateway-service-content[ContentResolverProvider]

  ContentApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
