services:
  CustomContentService:
    class: /CustomContent/Service/CustomContentService
    arguments:
      - '%services.custom-content.path%'
      - '%services.custom-content.schema%'
      - '@CustomContentResolverProvider'
      - '@CustomContentDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@CustomContentApolloServerBuilder'

  CustomContentResolverProvider:
    class: /CustomContent/Resolver/CustomContentResolverProvider
    arguments: []

  CustomContentApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
