parameters:
  ecomm:
    path: /_internal/ecomm

services:
  EcommService:
    class: //@inviqa/viper-gateway-service-ecomm[EcommService]
    arguments:
      - '%ecomm.path%'
      - './node_modules/@inviqa/viper-gateway-service-ecomm/src/typedef/schema.graphql'
      - '@EcommResolverProvider'
      - '@CartDataSourceProvider'
      - '@CheckoutDataSourceProvider'
      - '@OrderDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@EcommApolloServerBuilder'

  EcommResolverProvider:
    class: //@inviqa/viper-gateway-service-ecomm[EcommResolverProvider]

  EcommApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
