services:
  EcommService:
    class: //@inviqa/viper-gateway-service-ecomm[EcommService]
    arguments:
      - '%services.ecomm.path%'
      - '%services.ecomm.schema%'
      - '@EcommResolverProvider'
      - '@CartDataSourceProvider'
      - '@CheckoutDataSourceProvider'
      - '@OrderDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@EcommApolloServerBuilder'

  EcommResolverProvider:
    class: //@inviqa/viper-gateway-service-ecomm[EcommResolverProvider]

  EcommApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
