services:
  GatewayApp:
    class: //@inviqa/viper-gateway[GatewayApp]
    factory: ['@GatewayAppFactory', 'create']
    arguments:
      - '@GatewayKoa'
      - '@GatewayServiceRunner'
      - '@GatewayServices'
      - '%gateway.listen%'

  GatewayServices:
    class: //@inviqa/viper-gateway[GatewayServiceList]
    factory: ['@GatewayServiceListFactory', 'create']
    arguments:
      - '@/Gateway/GatewayService[GatewayService]'

  GatewayKoa:
    class: //koa[default]
    factory: ['@KoaFactory', 'create']
    arguments: ['@KoaCorsMiddleware']
