parameters:
  helloworld:
    path: /_internal/hello-world

services:
  /HelloWorld/HelloWorldService[HelloWorldService]:
    arguments:
      - '%helloworld.path%'
      - './src/HelloWorld/typedef/hello-world.graphql'
      - '@/HelloWorld/ResolverProvider[ResolverProvider]'
      - '@/HelloWorld/DataSource/MockHelloWorldDataSource[MockHelloWorldDataSource]'
      - '@GatewayServiceRunner'
      - '@HelloWorldApolloServerBuilder'

  /HelloWorld/ResolverProvider[ResolverProvider]: ~

  /HelloWorld/DataSource/MockHelloWorldDataSource[MockHelloWorldDataSource]: ~

  HelloWorldApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
