parameters:
  helloworld:
    path: /_internal/hello-world

services:
  HelloWorldService:
    class: /HelloWorld/HelloWorldService
    arguments:
      - '%helloworld.path%'
      - './src/HelloWorld/typedef/hello-world.graphql'
      - '@HelloWorldResolverProvider'
      - '@HelloWorldDataSource'
      - '@GatewayServiceRunner'
      - '@HelloWorldApolloServerBuilder'

  HelloWorldResolverProvider:
    class: /HelloWorld/ResolverProvider
    arguments: []

  HelloWorldDataSource:
    class: /HelloWorld/DataSource/MockHelloWorldDataSource
    arguments: []

  HelloWorldApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
