services:
  MenuService:
    class: //@inviqa/viper-gateway-service-menu[MenuService]
    arguments:
      - '%services.menu.path%'
      - '%services.menu.schema%'
      - '@MenuResolverProvider'
      - '@MenuDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@MenuApolloServerBuilder'

  MenuResolverProvider:
    class: //@inviqa/viper-gateway-service-menu[MenuResolverProvider]

  MenuApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
