parameters:
  menu:
    path: /_internal/menu

services:
  MenuService:
    class: //@inviqa/viper-gateway-service-menu[MenuService]
    arguments:
      - '%menu.path%'
      - './node_modules/@inviqa/viper-gateway-service-menu/src/typedef/schema.graphql'
      - '@MenuResolverProvider'
      - '@MenuDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@MenuApolloServerBuilder'

  MenuResolverProvider:
    class: //@inviqa/viper-gateway-service-menu[MenuResolverProvider]

  MenuApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
