parameters:
  routing:
    path: /_internal/routing

services:
  RoutingService:
    class: //@inviqa/viper-gateway-service-routing[RoutingService]
    arguments:
      - '%routing.path%'
      - './node_modules/@inviqa/viper-gateway-service-routing/src/typedef/schema.graphql'
      - '@RoutingResolverProvider'
      - '@CatalogRoutingDataSourceProvider'
      - '@ContentRoutingDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@RoutingApolloServerBuilder'

  RoutingResolverProvider:
    class: //@inviqa/viper-gateway-service-routing[RoutingResolverProvider]

  RoutingApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
