services:
  RoutingService:
    class: //@inviqa/viper-gateway-service-routing[RoutingService]
    arguments:
      - '%services.routing.path%'
      - '%services.routing.schema%'
      - '@RoutingResolverProvider'
      - '@CatalogRoutingDataSourceProvider'
      - '@ContentRoutingDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@RoutingApolloServerBuilder'

  RoutingResolverProvider:
    class: //@inviqa/viper-gateway-service-routing[RoutingResolverProvider]

  RoutingApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
