services:
  UserService:
    class: //@inviqa/viper-gateway-service-user[UserService]
    arguments:
      - '%services.user.path%'
      - '%services.user.schema%'
      - '@UserResolverProvider'
      - '@UserDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@UserApolloServerBuilder'

  UserResolverProvider:
    class: //@inviqa/viper-gateway-service-user[UserResolverProvider]

  UserDataSourceProvider:
    class: //@inviqa/viper-gateway-service-user[InMemoryUserDataSourceProvider]

  UserApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
