parameters:
  user:
    path: /_internal/user

services:
  UserService:
    class: //@inviqa/viper-gateway-service-user[UserService]
    arguments:
      - '%user.path%'
      - './node_modules/@inviqa/viper-gateway-service-user/src/typedef/schema.graphql'
      - '@UserResolverProvider'
      - '@UserDataSourceProvider'
      - '@GatewayServiceRunner'
      - '@UserApolloServerBuilder'

  UserResolverProvider:
    class: //@inviqa/viper-gateway-service-user[UserResolverProvider]

  UserDataSourceProvider:
    class: //@inviqa/viper-gateway-service-user[InMemoryUserDataSourceProvider]

  UserApolloServerBuilder:
    class: //@inviqa/viper-apollo[ApolloServerBuilder]
    factory: ['@ApolloServerBuilderFactory', 'create']
    arguments:
      - '@Logger'
      - '%gateway.server%'
      - '@ApolloServerPluginProviderList'
