import: services.yml

services:
  ContentDataSource:
    class: //@inviqa/viper-gateway-service-content[InMemoryContentDataSource]
    arguments: []

  CatalogDataSource:
    class: //@inviqa/viper-gateway-service-catalog[InMemoryCatalogDataSource]
    arguments: ['@InMemoryCatalogClient']

  InMemoryCatalogClient:
    class: //@inviqa/viper-gateway-service-catalog[InMemoryCatalogClient]
    arguments: []

  ContentRoutingDataSource:
    class: //@inviqa/viper-gateway-service-routing[InMemoryRoutingDataSource]
    arguments: []

  CatalogRoutingDataSource:
    class: //@inviqa/viper-gateway-service-routing[InMemoryRoutingDataSource]
    arguments: []

  MenuDataSource:
    class: //@inviqa/viper-gateway-service-menu[InMemoryMenuDataSource]
    arguments: []

  OrderDataSource:
    class: //@inviqa/viper-gateway-service-ecomm[InMemoryOrderDataSource]
    arguments: ['@InMemoryOrderClient']

  CheckoutDataSource:
    class: //@inviqa/viper-gateway-service-ecomm[InMemoryCheckoutDataSource]
    arguments: ['@InMemoryCheckoutClient']

  CartDataSource:
    class: //@inviqa/viper-gateway-service-ecomm[InMemoryCartDataSource]
    arguments: ['@InMemoryCartClient']

  InMemoryOrderClient:
    class: //@inviqa/viper-gateway-service-ecomm[InMemoryOrderClient]
    arguments: ['@InMemoryCheckoutClient']

  InMemoryCheckoutClient:
    class: //@inviqa/viper-gateway-service-ecomm[InMemoryCheckoutClient]
    arguments: ['@InMemoryCartClient']

  InMemoryCartClient:
    class: //@inviqa/viper-gateway-service-ecomm[InMemoryCartClient]
    arguments: ['@InMemoryCatalogClient']

  ConfigDataSource:
    class: //@inviqa/viper-gateway-service-config[InMemoryConfigDataSource]
    arguments: ['@InMemoryConfigRepository']

  InMemoryConfigRepository:
    class: //@inviqa/viper-gateway-service-config[InMemoryConfigRepository]
    arguments: []

  AuthDataSource:
    class: //@inviqa/viper-gateway-service-auth[InMemoryAuthDataSource]
    arguments: ['%env(AUTH_TOKEN_SECRET)%']
