import:
  - core/*.yml
  - backend-services/mock-data/*.yml
  - backend-services/mock-data/overrides/*.override.yml
  - services/*.yml
  - services/overrides/*.override.yml
  - apps/*.yml
  - main.yml
