import:
  - core/*.yml
  - backend-services/magento/*.yml
  - backend-services/magento/overrides/*.override.yml
  - backend-services/drupal/*.yml
  - services/*.yml
  - apps/*.yml
  - generated.yml
  - main.yml
