FROM {{ @('app.build.from') }} as node

RUN echo 'APT::Install-Recommends 0;' >> /etc/apt/apt.conf.d/01norecommends \
 && echo 'APT::Install-Suggests 0;' >> /etc/apt/apt.conf.d/01norecommends \
 && apt-get update -qq \
 && DEBIAN_FRONTEND=noninteractive apt-get -qq -y --no-install-recommends install \
  # package dependencies \
   autoconf \
   automake \
   build-essential \
   ca-certificates \
   curl \
   git \
   iproute2 \
   jq \
   nano \
   nasm \
   patch \
   pv \
   rsync \
   supervisor \
   unzip \
   wget \
  # clean \
 && apt-get auto-remove -qq -y \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

COPY .my127ws/docker/image/node/root /

WORKDIR /app

ENV APP_DEVELOPMENT={{ @('app.development') }}
ENV APP_DYNAMIC={{ @('app.dynamic') }}

{% if @('app.dynamic') == 'yes' %}

USER root
VOLUME /app
VOLUME /home/node/application
ENTRYPOINT ["/entrypoint.dynamic.sh"]

{% else %}

RUN chown node:node /app
COPY --chown=node:node .my127ws/application  /home/node/application
COPY --chown=node:node ./                    /app
RUN cd /app/app/client/config; mv default.build.js default.js
USER node
RUN app build
USER root
ENTRYPOINT ["/entrypoint.sh"]

{% endif %}
