services:
  CatalogRoutingDataSourceProvider:
    class: //@inviqa/viper-gateway-service-routing[SprykerRoutingDataSourceProvider]
    arguments:
      - '@SprykerGlueClientProvider'
      - '@CatalogRoutingDataTransformer'

  CatalogRoutingDataTransformer:
    class: //@inviqa/viper-gateway-service-routing[SprykerRoutingDataTransformer]
