services:
  CatalogDataSourceProvider:
    class: //@inviqa/viper-gateway-service-catalog[InMemoryCatalogDataSourceProvider]
    arguments: ['@InMemoryCatalogClient']

  InMemoryCatalogClient:
    class: //@inviqa/viper-gateway-service-catalog[InMemoryCatalogClient]
    arguments: []
