services:
  CatalogDataSourceProvider:
    class: //@inviqa/viper-gateway-service-catalog[BigcommerceCatalogDataSourceProvider]
    arguments:
      - '@BigcommerceGraphqlClientProvider'
      - '@BigcommerceRestV3ClientProvider'
      - '@CatalogProductDataTransformer'

  CatalogProductDataTransformer:
    class: //@inviqa/viper-gateway-service-catalog[BigcommerceProductDataTransformer]
