services:
  CatalogRoutingDataSourceProvider:
    class: //@inviqa/viper-gateway-service-routing[BigcommerceRoutingDataSourceProvider]
    arguments:
      - '@BigcommerceGraphqlClientProvider'
      - '@CatalogRoutingDataTransformer'

  CatalogRoutingDataTransformer:
    class: //@inviqa/viper-gateway-service-routing[BigcommerceRoutingDataTransformer]
