services:
  CatalogRoutingDataSourceProvider:
    class: //@inviqa/viper-gateway-service-routing[MagentoRoutingDataSourceProvider]
    arguments:
      - '@MagentoGraphqlClientProvider'
      - '@CatalogRoutingDataTransformer'

  CatalogRoutingDataTransformer:
    class: //@inviqa/viper-gateway-service-routing[MagentoRoutingDataTransformer]
