schema:
  - http://localhost:4000/graphql
  - src/typedef/**/*.ts
documents: src/hooks/apollo/documents/**/*.graphql
extensions:
  viper:
    type: gateway
  codegen:
    generates:
      src/hooks/apollo/generated.ts:
        plugins:
          - typescript
          - typescript-operations
          - typescript-react-apollo
          - typescript-apollo-client-helpers
        config:
          pureMagicComment: true
          enumsAsConst: true
          federation: true
          noSchemaStitching: true
          withComponent: false
          withHOC: false
          withHooks: true
          withMutationFn: false
          withRefetchFn: false
          withResultType: false
          gqlImport: '@apollo/client#gql'
          documentNodeImport: '@apollo/client#DocumentNode'
          documentMode: documentNode
