apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.resourcePrefix }}viper-client
  labels:
    app.service: {{ .Values.resourcePrefix }}viper-client
  annotations:
    argocd.argoproj.io/sync-wave: "15"
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app.service: {{ .Values.resourcePrefix }}viper-client
  template:
    metadata:
      labels:
        app.service: {{ .Values.resourcePrefix }}viper-client
    spec:
      containers:
      - name: viper-client
        {{- if .Values.app.gateway.env }}
        env:
{{- toYaml .Values.app.client.env | nindent 10 }}
        {{- end }}
        image: {{ .Values.app.image }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{ .Values.app.client.port }}
        resources:
          limits:
            memory: {{ .Values.app.client.resources.memory }}
          requests:
            memory: {{ .Values.app.client.resources.memory }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.app.client.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
{{- if .Values.app.image_pull_config }}
      imagePullSecrets:
      - name: {{ .Values.resourcePrefix }}image-pull-config
{{- end }}
      restartPolicy: Always
      enableServiceLinks: false
status: {}
