apiVersion: v1
kind: Service
metadata:
  labels:
    app.service: {{ .Values.app.resourcePrefix }}viper-client
  name: {{ .Values.app.resourcePrefix }}viper-client
spec:
  ports:
  - name: http
    port: 80
    targetPort: {{ .Values.app.client.port }}
  selector:
    app.service: {{ .Values.app.resourcePrefix }}viper-client
status:
  loadBalancer: {}
